security:
  basic:
    enabled: false
management:
  security:
    enabled: false
spring:
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: wombat.rmq.cloudamqp.com
    port: 5672
    username: hbrujcae
    password: C3535ixtNaXAgGzcklDnkv9sIFYYBSp-
    virtual-host: hbrujcae
  boot:
    admin:
      url: http://localhost:8081  
logging:
  level:
    com.dcsands: Error    
message: Hello World
feature.isEnabled: false    