security:
  basic:
    enabled: false
management:
  security:
    enabled: false
spring:
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: wombat.rmq.cloudamqp.com
    port: 5672
    username: hbrujcae
    password: C3535ixtNaXAgGzcklDnkv9sIFYYBSp-
    virtual-host: hbrujcae
logging:
  level:
    com.dcsands: DEBUG    
message: Hello ARMS
feature.isEnabled: true    